baseURL = 'https://libitum.github.io/'
languageCode = 'zh-cn'
title = '立波吞'
theme = 'm10c'

sectionPagesMenu = 'main'

[services]
  [services.googleAnalytics]
    ID = 'G-ZWHV2C1CGY'
  [services.disqus]
    shortname = 'libitum-github'
