baseURL = 'https://libitum.github.io/'
languageCode = 'zh-cn'
title = '立波吞'
theme = 'tailwind'

sectionPagesMenu = 'main'

[services]
  [services.googleAnalytics]
    ID = 'G-ZWHV2C1CGY'

[params]
# giscus is comments system powered by GitHub Discussions
# generate configurations from https://giscus.app/
[params.giscus]
  enabled = true
  repo = "Libitum/libitum.github.com"
  repoID = "MDEwOlJlcG9zaXRvcnkyOTg2NzM1"
  category = "Announcements"
  categoryID = "DIC_kwDOAC2S784CbtAM"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  lang = "en"
  loading = "lazy"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20
