baseURL = 'https://libitum.github.io/'
languageCode = 'zh-cn'
title = '立波吞'
theme = 'm10c'

sectionPagesMenu = 'main'
author = 'libitum'
description = '码农'

[services]
  [services.googleAnalytics]
    ID = 'G-ZWHV2C1CGY'